// Code generated by "stringer -type=Measurement -trimprefix=Measurement"; DO NOT EDIT.

package seekpo

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MeasurementValue-0]
	_ = x[MeasurementStatus-1]
}

const _Measurement_name = "ValueStatus"

var _Measurement_index = [...]uint8{0, 5, 11}

func (i Measurement) String() string {
	if i < 0 || i >= Measurement(len(_Measurement_index)-1) {
		return "Measurement(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Measurement_name[_Measurement_index[i]:_Measurement_index[i+1]]
}
